### ISSUE TITLE
Make minimum event temperature its own argument for firefinder()

### ISSUE THREAD

**Issue by daterdots** [Geocene/sumsarizer#7]
Before, we decided to use `primary_threshold` as the minimum temperature within a cooking event for it to be considered an event. However, that is not working out well in practice. Let's make a new argument called `min_event_temp`. Ideally, this argument could be null by default, and the events wouldn't need to have any minimum temperature to qualify as an event.

**Comment by jeremyrcoyle** [comment]
fixed in https://github.com/Geocene/sumsarizer/commit/17b94f9118e6dbdaddaebeeb1971b25019451b97
