### ISSUE TITLE
Add metadata.csv to S3 

### ISSUE THREAD

**Issue by daterdots** [Geocene/sumsarizer#8]
- [x] add it to S3
- [x] download it when we download the files
- [x] make example code to do this `metadata <- read.csv("metadata.csv")`
- [x] make sure the project knits
- [x] remove CSV from the repo

**Comment by jeremyrcoyle** [comment]
Fixed in https://github.com/Geocene/sumsarizer/commit/dcb1510c23fc7370f863b06c2ea7181e963924e4
